### ISSUE TITLE
Use runST and ST instead of IO and unsafePerformIO

### ISSUE THREAD

**Issue by axman6** [agrafix/superrecord#15]
It appears all of the functions used to create and modify all the `Small(Mutable)Array#`'s also work in the `ST` monad, which would mean it should be possible to replace all
```haskell
unsafePerformIO $! IO $ \s -> ...
```
with 
```haskell
runST $! ST $ \s -> ...
```
and hopefully proceed exactly the same code while avoid the unnecessarily using the unutterable function.

**Comment by agrafix** [comment]
Should work! Feel free to send a PR :)

**Comment by reactormonk** [comment]
Fixed by https://github.com/agrafix/superrecord/pull/16
