### ISSUE TITLE
newtype Rec?

### ISSUE THREAD

**Issue by axman6** [agrafix/superrecord#25]
Is there any reason why Rec isn't a newtype? Not sure if it would make much difference with the internal representation being a SmallArray#, but it doesn't look like it should hurt to make it a newtype.

**Comment by neongreen** [comment]
It can't be a newtype: `A newtype cannot have an unlifted argument type`. If we want `Rec` to be a normal lifted type, it has to be a `data`.

It can be an unlifted newtype with -XUnliftedNewtype, but that would make users' lives harder, I think.
