### ISSUE TITLE
Experience with GHCJS

### ISSUE THREAD

**Issue by 3noch** [agrafix/superrecord#6]
Since this uses lower level GHC APIs I wonder how it performs when used in JS generated by GHCJS. Does anyone have info about this?

**Comment by agrafix** [comment]
Sorry for the late reply - the current HEAD has two GHCJS modes, one using the low level GHC APIs and one using native JS objects as records. I would like to do some benchmarks here, but have not gotten to it yet. Would be happy to help if you are interested in trying to do this :)
